---
- name: Test random filter
  hosts: all
  become: yes
  gather_facts: False
  vars:
  tasks:
    - apt: "name={{ item }} state=present"
      with_items:
        - git
        - wget
        - curl
        - unzip
        - openssl
        - systemd
        - python-pip
        - python3
        - python3-pip
        - python3-dev
        - postgresql
        - postgresql-contrib
        - postgresql-server-dev-10

    - name: Install psycopg2
      shell: |
        pip install psycopg2
      become: true

    - name: Create a new database with name "confluence"
      community.general.postgresql_db:
        name: confluence
      become_user: postgres

    - name: Create appclient user password
      community.general.postgresql_user:
        name: confluence
        password: "confluence"
      become_user: postgres

    - name: Download jdk 8
      get_url:
        url: https://github.com/frekele/oracle-java/releases/download/8u201-b09/jdk-8u201-linux-x64.tar.gz
        dest: /home/vagrant/

    - name: Install jdk8
      shell: |
        sudo mkdir /usr/lib/jvm
        cd /usr/lib/jvm
        sudo tar -xvzf /home/vagrant/jdk-8u201-linux-x64.tar.gz
      become: true

    - name: Copy plugin list to Jenkins home
      copy:
        src: "environment"
        dest: "/etc/"
      become: true

    - name: alternatives link for "java"
      alternatives:
        name: java
        link: /usr/bin/java
        path: "/usr/lib/jvm/jdk1.8.0_201/bin/java"
      become: true

    - name: alternatives link for "javac"
      alternatives:
        name: javac
        link: /usr/bin/javac
        path: "/usr/lib/jvm/jdk1.8.0_201/bin/javac"
      become: true

    - name: alternatives link for "jar"
      alternatives:
        name: jar
        link: /usr/bin/jar
        path: "/usr/lib/jvm/jdk1.8.0_201/bin/jar"
      become: true

    - name: Download confluence
      get_url:
        url: https://product-downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-7.4.5.tar.gz
        dest: /home/vagrant

    - name: Install confluence
      shell: |
        mkdir /home/vagrant/confluence
        tar -xzf atlassian-confluence-7.4.5.tar.gz -C /home/vagrant/confluence
        cd /home/vagrant/confluence
        tar -xzf atlassian-confluence-7.4.5.tar
        chown -R vagrant /home/vagrant/confluence
        chmod -R u=rwx,go-rwx /home/vagrant/confluence
        mkdir /home/vagrant/confluence-home
        chown -R vagrant /home/vagrant/confluence-home
        chmod -R u=rwx,go-rwx /home/vagrant/confluence-home
      args:
        creates: "/home/vagrant/confluence/atlassian-confluence-7.4.5/bin/start-confluence.sh"
      become: true

    - name: Copy Confluence home to Confluence
      copy:
        src: "confluence-init.properties"
        dest: "/home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/classes"
      become: true

    - name: Copy Confluence service
      copy:
        src: "confluence.service"
        dest: "/etc/systemd/system/"
      become: true

    - name: Download SSO Plugin
      shell: wget --content-disposition -P /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins/ "https://marketplace.atlassian.com/download/apps/1218360"
      tags: dot.confluence
      become: true

    - name: Download Bob Swift Atlassian Add-ons - Code Pro
      shell: wget --content-disposition -P /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins/ "https://marketplace.atlassian.com/download/apps/1212539"
      tags: dot.confluence
      become: true

    - name: Download Conditional Multiexcerpt
      shell: wget --content-disposition -P /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins/ "https://marketplace.atlassian.com/download/apps/1217620"
      tags: dot.confluence
      become: true

    - name: Download Table Filter and Charts for Confluence
      shell: wget --content-disposition -P /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins/ "https://marketplace.atlassian.com/download/apps/27447"
      tags: dot.confluence
      become: true

    #OBR STUFF

    - name: Download OBR plugins and extract them (Lucidchart, Team Calendar, Balsamiq Wireframes, draw.io, Gliffy, Scroll HTML, Scroll Translation, Scroll Versions)
      shell: |
        mkdir /tmp/plugins-obr
        mkdir /tmp/plugins-obr/plugins-unziped
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/1213835" 
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/72307"
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/256"
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/1210933"
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/254"
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/420604"
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/1211616"
        wget --content-disposition -P /tmp/plugins-obr/ "https://marketplace.atlassian.com/download/apps/1210818"
        cd /tmp/plugins-obr/plugins-unziped
        unzip -o /tmp/plugins-obr/\*
        mv /tmp/plugins-obr/plugins-unziped/*.jar /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins/
        mv /tmp/plugins-obr/plugins-unziped/dependencies/*.jar /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins/
        rm -R /tmp/plugins-obr
      become: true

    - name: Start Confluence
      shell: |
        chown -R vagrant /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins
        chmod -R u=rwx,go-rwx /home/vagrant/confluence/atlassian-confluence-7.4.5/confluence/WEB-INF/atlassian-bundled-plugins
        sudo systemctl enable confluence
        sudo systemctl start confluence
      become: true
